### ISSUE TITLE
question

### ISSUE THREAD

**Issue by seospace** [Xeoncross/goworkqueue#1]
````
for w := 1; w <= workers; w++ {
		q.workers <- q.worker(w, callback)
}
````
Can you explain ````w <= workers````

**Comment by xeoncross** [comment]
Sure, that means while the integer `w` is less-than-or-equal to (`<=`) the number of workers desired we create a worker.

**Comment by seospace** [comment]
Oh right i wasn't thinking, its a normal less or equal WOW 🗡
